// <auto-generated />
using System;
using Database.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    partial class ScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.EntityFrameworkCore.Model.ConstructionTask", b =>
                {
                    b.Property<string>("TaskID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("ActualDuration")
                        .HasColumnType("float");

                    b.Property<int>("ActualResources")
                        .HasColumnType("int");

                    b.Property<string>("Craft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EstimatedDuration")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedResources")
                        .HasColumnType("int");

                    b.Property<string>("Operation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("ParentID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Database.EntityFrameworkCore.Model.ConstructionTask", b =>
                {
                    b.HasOne("Database.EntityFrameworkCore.Model.ConstructionTask", "ParentTask")
                        .WithMany("Precedence")
                        .HasForeignKey("ParentID");
                });
#pragma warning restore 612, 618
        }
    }
}
