//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleAlgorithmLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScheduleAlgorithmLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Structural Foundation,5,1,VVS,
        ///1.0,z0,Sewage,1,2,Concrete,0.0
        ///2.0,z1,Piping,9,2,Concrete,1.0
        ///3.0,z1,Piping,9,2,Painter,2.0
        ///4.0,z2,Structural Foundation,3,3,Concrete,3.0
        ///5.0,z2,Interior Walls,1,1,VVS,4.0
        ///6.0,z3,Interior Walls,7,3,Carpenter,5.0
        ///7.0,z3,Floor,6,1,Painter,6.0
        ///8.0,z4,Gypsum,9,2,Electrician,7.0
        ///9.0,z4,Floor,2,1,VVS,8.0
        ///.
        /// </summary>
        internal static string dataset10 {
            get {
                return ResourceManager.GetString("dataset10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Structural Foundation,4,1,Concrete,
        ///1.0,z0,Interior Walls,2,1,Carpenter,0.0
        ///2.0,z0,Gypsum,1,1,Electrician,1.0
        ///3.0,z0,Gypsum,1,3,Painter,2.0
        ///4.0,z0,Interior Walls,8,1,Painter,3.0
        ///5.0,z0,Structural Walls,8,1,Painter,4.0
        ///6.0,z0,Structural Walls,7,3,Carpenter,5.0
        ///7.0,z0,Structural Walls,9,2,Electrician,6.0
        ///8.0,z0,Structural Foundation,9,1,Carpenter,7.0
        ///9.0,z0,Piping,2,1,Electrician,8.0
        ///10.0,z0,Structural Foundation,2,1,VVS,9.0        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset100 {
            get {
                return ResourceManager.GetString("dataset100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Interior Walls,8,2,Concrete,
        ///1.0,z0,Electricity,2,1,Painter,0.0
        ///2.0,z0,Structural Walls,2,1,Carpenter,1.0
        ///3.0,z0,Structural Walls,4,2,VVS,2.0
        ///4.0,z0,Floor,2,2,Painter,3.0
        ///5.0,z0,Structural Walls,7,2,Electrician,4.0
        ///6.0,z0,Structural Walls,1,1,Painter,5.0
        ///7.0,z0,Interior Walls,8,1,Electrician,6.0
        ///8.0,z0,Structural Walls,2,1,VVS,7.0
        ///9.0,z0,Interior Walls,3,1,Carpenter,8.0
        ///10.0,z0,Gypsum,4,1,Concrete,9.0
        ///11.0,z0,Gypsum,7,2,El [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset1000 {
            get {
                return ResourceManager.GetString("dataset1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Sewage,4,2,Electrician,
        ///1.0,z0,Piping,9,2,Electrician,0.0
        ///2.0,z0,Electricity,9,3,Concrete,1.0
        ///3.0,z0,Piping,2,2,Carpenter,2.0
        ///4.0,z0,Interior Walls,9,1,VVS,3.0
        ///5.0,z0,Structural Walls,5,2,Painter,4.0
        ///6.0,z0,Interior Walls,7,1,Carpenter,5.0
        ///7.0,z0,Interior Walls,2,3,Painter,6.0
        ///8.0,z0,Floor,4,2,Painter,7.0
        ///9.0,z0,Floor,8,1,Electrician,8.0
        ///10.0,z0,Floor,2,3,VVS,9.0
        ///11.0,z0,Interior Walls,2,3,VVS,10.0
        ///12.0,z0,Gypsum,4,1,VVS, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset10000 {
            get {
                return ResourceManager.GetString("dataset10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Piping,2,2,Painter,
        ///1.0,z0,Structural Walls,1,3,Carpenter,0.0
        ///2.0,z0,Electricity,1,1,Concrete,1.0
        ///3.0,z0,Interior Walls,8,3,Electrician,2.0
        ///4.0,z0,Piping,4,3,Concrete,3.0
        ///5.0,z0,Electricity,1,1,Painter,4.0
        ///6.0,z0,Structural Walls,9,1,VVS,5.0
        ///7.0,z0,Structural Walls,4,1,Painter,6.0
        ///8.0,z0,Gypsum,2,1,VVS,7.0
        ///9.0,z0,Structural Walls,8,3,Concrete,8.0
        ///10.0,z0,Interior Walls,3,2,Concrete,9.0
        ///11.0,z0,Piping,7,1,VVS,10.0
        ///12.0,z0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset100000 {
            get {
                return ResourceManager.GetString("dataset100000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Structural Walls,2,2,VVS,
        ///1.0,z0,Structural Walls,1,3,Concrete,0.0
        ///2.0,z0,Gypsum,5,1,Carpenter,1.0
        ///3.0,z0,Floor,9,1,VVS,2.0
        ///4.0,z0,Gypsum,1,1,Concrete,3.0
        ///5.0,z0,Gypsum,8,3,Electrician,4.0
        ///6.0,z0,Electricity,5,1,VVS,5.0
        ///7.0,z0,Piping,3,2,Concrete,6.0
        ///8.0,z0,Interior Walls,7,3,Painter,7.0
        ///9.0,z0,Structural Walls,2,2,Painter,8.0
        ///10.0,z0,Structural Walls,5,3,Painter,9.0
        ///11.0,z0,Structural Walls,1,3,Electrician,10.0
        ///12.0,z0,I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset1000000 {
            get {
                return ResourceManager.GetString("dataset1000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Structural Foundation,6,2,Painter,
        ///1.0,z0,Interior Walls,4,1,Carpenter,0.0
        ///2.0,z0,Gypsum,7,1,Electrician,1.0
        ///3.0,z0,Interior Walls,8,1,VVS,2.0
        ///4.0,z0,Structural Foundation,6,1,Painter,3.0
        ///5.0,z0,Electricity,4,3,Painter,4.0
        ///6.0,z0,Interior Walls,6,2,Carpenter,5.0
        ///7.0,z0,Interior Walls,2,3,Painter,6.0
        ///8.0,z0,Sewage,9,3,VVS,7.0
        ///9.0,z0,Structural Walls,4,3,Concrete,8.0
        ///10.0,z0,Sewage,3,1,Painter,9.0
        ///11.0,z0,Sewage,9,1,Electric [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset1250 {
            get {
                return ResourceManager.GetString("dataset1250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Gypsum,3,2,Carpenter,
        ///1.0,z0,Structural Foundation,8,2,Electrician,0.0
        ///2.0,z0,Interior Walls,9,2,Electrician,1.0
        ///3.0,z0,Electricity,6,1,Concrete,2.0
        ///4.0,z0,Structural Walls,5,3,Concrete,3.0
        ///5.0,z0,Structural Walls,1,2,Electrician,4.0
        ///6.0,z0,Electricity,4,1,Electrician,5.0
        ///7.0,z0,Structural Walls,4,1,Painter,6.0
        ///8.0,z0,Floor,4,2,Electrician,7.0
        ///9.0,z0,Piping,5,3,VVS,8.0
        ///10.0,z0,Interior Walls,5,2,VVS,9.0
        ///11.0,z0,Sewage,5,3, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset1500 {
            get {
                return ResourceManager.GetString("dataset1500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Floor,8,2,Electrician,
        ///1.0,z0,Structural Foundation,3,1,Electrician,0.0
        ///2.0,z0,Sewage,2,2,Carpenter,1.0
        ///3.0,z0,Interior Walls,4,2,Electrician,2.0
        ///4.0,z0,Piping,8,3,Electrician,3.0
        ///5.0,z0,Floor,7,3,Electrician,4.0
        ///6.0,z0,Interior Walls,6,1,Concrete,5.0
        ///7.0,z0,Gypsum,3,1,Concrete,6.0
        ///8.0,z0,Interior Walls,4,3,Electrician,7.0
        ///9.0,z0,Interior Walls,1,3,VVS,8.0
        ///10.0,z0,Floor,4,1,Painter,9.0
        ///11.0,z0,Structural Walls,9,3,Carpente [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset1750 {
            get {
                return ResourceManager.GetString("dataset1750", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Floor,1,1,Electrician,
        ///1.0,z0,Structural Foundation,3,2,Carpenter,0.0
        ///2.0,z0,Structural Walls,3,2,Electrician,1.0
        ///3.0,z0,Sewage,8,1,Carpenter,2.0
        ///4.0,z0,Interior Walls,3,1,VVS,3.0
        ///5.0,z0,Sewage,4,3,Carpenter,4.0
        ///6.0,z0,Gypsum,7,3,Painter,5.0
        ///7.0,z0,Interior Walls,6,3,Painter,6.0
        ///8.0,z0,Gypsum,4,1,VVS,7.0
        ///9.0,z0,Piping,7,2,Painter,8.0
        ///10.0,z0,Piping,6,3,Concrete,9.0
        ///11.0,z0,Sewage,2,1,Electrician,10.0
        ///12.0,z0,Electricity,3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset2000 {
            get {
                return ResourceManager.GetString("dataset2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Structural Foundation,8,1,Painter,
        ///1.0,z0,Structural Foundation,9,1,Electrician,0.0
        ///2.0,z0,Structural Walls,5,2,Electrician,1.0
        ///3.0,z0,Gypsum,9,1,Concrete,2.0
        ///4.0,z0,Sewage,4,1,Carpenter,3.0
        ///5.0,z0,Structural Walls,6,1,Painter,4.0
        ///6.0,z0,Floor,4,1,Carpenter,5.0
        ///7.0,z0,Structural Walls,7,3,Concrete,6.0
        ///8.0,z0,Structural Walls,8,3,Painter,7.0
        ///9.0,z0,Sewage,7,1,VVS,8.0
        ///10.0,z0,Structural Walls,1,3,Carpenter,9.0
        ///11.0,z0,Gypsum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset250 {
            get {
                return ResourceManager.GetString("dataset250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Electricity,8,2,Painter,
        ///1.0,z0,Piping,7,3,Concrete,0.0
        ///2.0,z0,Structural Walls,9,2,VVS,1.0
        ///3.0,z0,Floor,8,2,Painter,2.0
        ///4.0,z0,Floor,6,1,VVS,3.0
        ///5.0,z0,Floor,3,1,Painter,4.0
        ///6.0,z0,Gypsum,2,1,VVS,5.0
        ///7.0,z0,Gypsum,4,1,Carpenter,6.0
        ///8.0,z0,Interior Walls,3,3,VVS,7.0
        ///9.0,z0,Electricity,7,2,Painter,8.0
        ///10.0,z1,Gypsum,4,1,Painter,9.0
        ///11.0,z1,Floor,9,3,Carpenter,10.0
        ///12.0,z1,Interior Walls,8,3,Painter,11.0
        ///13.0,z1,Interior W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset50 {
            get {
                return ResourceManager.GetString("dataset50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Gypsum,7,2,Painter,
        ///1.0,z0,Piping,5,1,Painter,0.0
        ///2.0,z0,Piping,2,1,VVS,1.0
        ///3.0,z0,Sewage,2,2,Painter,2.0
        ///4.0,z0,Structural Foundation,3,3,Electrician,3.0
        ///5.0,z0,Gypsum,6,2,Concrete,4.0
        ///6.0,z0,Structural Foundation,2,2,Painter,5.0
        ///7.0,z0,Structural Foundation,3,2,Electrician,6.0
        ///8.0,z0,Sewage,9,2,Carpenter,7.0
        ///9.0,z0,Structural Walls,8,1,Carpenter,8.0
        ///10.0,z0,Gypsum,4,2,Concrete,9.0
        ///11.0,z0,Piping,9,1,Electrician,10.0
        ///12. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset500 {
            get {
                return ResourceManager.GetString("dataset500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Electricity,6,1,Electrician,
        ///1.0,z0,Sewage,3,3,Painter,0.0
        ///2.0,z0,Interior Walls,8,1,Electrician,1.0
        ///3.0,z0,Floor,3,2,VVS,2.0
        ///4.0,z0,Floor,4,1,Carpenter,3.0
        ///5.0,z0,Structural Foundation,6,2,Electrician,4.0
        ///6.0,z0,Electricity,4,1,Painter,5.0
        ///7.0,z0,Sewage,2,1,Electrician,6.0
        ///8.0,z0,Electricity,7,3,Carpenter,7.0
        ///9.0,z0,Sewage,5,3,Electrician,8.0
        ///10.0,z0,Gypsum,1,3,Concrete,9.0
        ///11.0,z0,Electricity,7,2,Electrician,10.0
        ///12.0,z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset5000 {
            get {
                return ResourceManager.GetString("dataset5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///0.0,z0,Floor,6,1,Carpenter,
        ///1.0,z0,Sewage,8,1,Electrician,0.0
        ///2.0,z0,Electricity,8,2,Carpenter,1.0
        ///3.0,z0,Structural Foundation,5,2,Concrete,2.0
        ///4.0,z0,Interior Walls,4,2,Carpenter,3.0
        ///5.0,z0,Sewage,4,1,VVS,4.0
        ///6.0,z0,Floor,5,2,Concrete,5.0
        ///7.0,z0,Piping,9,2,Concrete,6.0
        ///8.0,z0,Interior Walls,2,3,Concrete,7.0
        ///9.0,z0,Electricity,5,1,Painter,8.0
        ///10.0,z0,Floor,3,2,Painter,9.0
        ///11.0,z0,Gypsum,7,2,Painter,10.0
        ///12.0,z0,Structural Found [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataset750 {
            get {
                return ResourceManager.GetString("dataset750", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///1,z1,Structural Foundation,2,2,Concrete,
        ///1.1,z1,Sewage,1,2,VVS,1
        ///1.2,z1,Floor,2,2,Concrete,1.1
        ///1.3,z1,Structural Walls,3,3,Concrete,1.2
        ///1.4,z1,Interior Walls,2,2,Carpenter,1.9
        ///1.5,z1,Electricity,2,1,Electrician,1.4
        ///1.6,z1,Piping,1,1,VVS,1.3
        ///1.7,z1,Gypsum,4,2,Carpenter,1.6
        ///1.8,z1,Painting,4,2,Painter,1.7
        ///1.9,z1,Finish,5,2,Carpenter,1.1
        ///.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order;
        ///1.0,z1,Structural Foundation,2,2,Concrete,;
        ///1.1,z1,Sewage,1,2,VVS,1.0;
        ///1.2,z1,Floor,2,2,Concrete,1.1;
        ///1.3,z1,Structural Walls,3,3,Concrete,1.2;
        ///1.4,z1,Interior Walls,2,2,Carpenter,5.2;
        ///1.5,z1,Electricity,2,1,Electrician,1.4;
        ///1.6,z1,Piping,1,1,VVS,1.5;
        ///1.7,z1,Gypsum,4,2,Carpenter,1.6;
        ///1.8,z1,Painting,4,2,Painter,1.7;
        ///1.9,z1,Finish,5,2,Carpenter,1.8;
        ///,,,,,,;
        ///2.0,z2,Structural Foundation,2,2,Concrete,1.0;
        ///2.1,z2,Sewage,1,2,VVS,1.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tinydataset {
            get {
                return ResourceManager.GetString("tinydataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///1.0,z1,Structural Foundation,2,2,Concrete,
        ///1.1,z1,Sewage,1,2,VVS,1.0
        ///1.2,z1,Floor,2,2,Concrete,1.1
        ///1.3,z1,Structural Walls,3,3,Concrete,1.2
        ///1.4,z1,Interior Walls,2,2,Carpenter,5.2
        ///1.5,z1,Electricity,2,1,Electrician,1.4
        ///1.6,z1,Piping,1,1,VVS,1.5
        ///1.7,z1,Gypsum,4,2,Carpenter,1.6
        ///1.8,z1,Painting,4,2,Painter,1.7
        ///1.9,z1,Finish,5,2,Carpenter,1.8
        ///,,,,,,
        ///2.0,z2,Structural Foundation,2,2,Concrete,1.0
        ///2.1,z2,Sewage,1,2,VVS,2.0
        ///2.2,z2,Floo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tinydatasetFewerConstraints {
            get {
                return ResourceManager.GetString("tinydatasetFewerConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///1.0,z1,Structural Foundation,2,2,Concrete,
        ///1.1,z1,Sewage,1,2,VVS,1.0
        ///1.2,z1,Floor,2,2,Concrete,1.1
        ///1.3,z1,Structural Walls,3,3,Concrete,1.2
        ///1.4,z1,Interior Walls,2,2,Carpenter,1.3
        ///1.5,z1,Electricity,2,1,Electrician,1.4
        ///1.6,z1,Piping,1,1,VVS,1.5
        ///1.7,z1,Gypsum,4,2,Carpenter,1.6
        ///1.8,z1,Painting,4,2,Painter,1.7;1.3
        ///1.9,z1,Finish,5,2,Carpenter,1.8;1.4
        ///.
        /// </summary>
        internal static string tinytinydataset {
            get {
                return ResourceManager.GetString("tinytinydataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Zone,Task operation,Duration,Resources,Craft,Construciton order
        ///1.0,z1,Structural Foundation,2,2,Concrete,
        ///1.1,z1,Sewage,1,2,VVS,1.0
        ///1.2,z1,Floor,2,2,Concrete,1.1
        ///1.3,z1,Structural Walls,3,3,Concrete,1.2;1.5
        ///1.4,z1,Interior Walls,2,2,Carpenter,1.3
        ///1.5,z1,Electricity,2,1,Electrician,1.4
        ///1.6,z1,Piping,1,1,VVS,1.5
        ///1.7,z1,Gypsum,4,2,Carpenter,1.6
        ///1.8,z1,Painting,4,2,Painter,1.7;1.3
        ///1.9,z1,Finish,5,2,Carpenter,1.8;1.4
        ///.
        /// </summary>
        internal static string tinytinydatasetWithCycle {
            get {
                return ResourceManager.GetString("tinytinydatasetWithCycle", resourceCulture);
            }
        }
    }
}
